const CoinsActionTypes = {
    SELECT_COIN: 'SELECT_COIN',
    FETCH_COINS_START: 'FETCH_COINS_START',
    FETCH_COINS_SUCCESS: 'FETCH_COINS_SUCCESS',
    FETCH_COINS_FAILURE: 'FETCH_COINS_FAILURE',
    ADD_COINS_START: 'ADD_COINS_START',
    ADD_COINS_SUCCESS: 'ADD_COINS_SUCCESS',
    ADD_COINS_FAILURE: 'ADD_COINS_FAILURE',
    SHOW_REMOVE_BUTTON: 'SHOW_REMOVE_BUTTON',
    REMOVE_COINS_START: 'REMOVE_COINS_START',
    REMOVE_COINS_SUCCESS: 'REMOVE_COINS_SUCCESS',
    REMOVE_COINS_FAILURE: 'REMOVE_COINS_FAILURE',
  };
  
  export default CoinsActionTypes;