const CoinsActionTypes = {
    FETCH_COINS_START: 'FETCH_COINS_START',
    FETCH_COINS_SUCCESS: 'FETCH_COINS_SUCCESS',
    FETCH_COINS_FAILURE: 'FETCH_COINS_FAILURE',
    ADD_COINS_START: 'ADD_COINS_START',
    ADD_COINS_SUCCESS: 'ADD_COINS_SUCCESS',
    ADD_COINS_FAILURE: 'ADD_COINS_FAILURE'
  };
  
  export default CoinsActionTypes;